title: Demo Page
author: ibelong2u
email: contact@aditya.sh
description: > # this means to ignore newlines until "baseurl:"
  Demo site for exploring gihub pages.

theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
